# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use Ubuntu 22.04 LTS
  config.vm.box = "ubuntu/jammy64"
  
  # VM configuration
  config.vm.hostname = "devops-userapi"
  
  # Network configuration
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 6379, host: 6379, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Sync folders
  config.vm.synced_folder "./userapi", "/home/vagrant/userapi", 
    type: "virtualbox",
    owner: "vagrant",
    group: "vagrant"
  
  # Provider configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "devops-userapi-vm"
    vb.memory = "2048"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  
  # Provision with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "iac/playbooks/main.yml"
    ansible.inventory_path = "iac/playbooks/inventory.ini"
    ansible.verbose = "v"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end
